contributors:
  - name: "Alex Bryant"
    username: ""
    year: 2020
  - name: "May Jue"
    username: ""
    year: 2021
  - name: "Sandesh Lamichhane "
    username: ""
    year: 2022
  - name: "Hila Manalai"
    username: ""
    year: 2022
  - name: "Luis Riera"
    username: ""
    year: 2022
  - name: "Liberty Muposta"
    username: ""
    year: 2022
  - name: "Ebenezer Ayisi"
    username: ""
    year: 2023
  - name: "Gaston Jarju"
    username: ""
    year: 2023
  - name: "Karina Agliullova"
    username: ""
    year: 2023
  - name: "Zach Neill"
    username: ""
    year: 2023
  - name: "Tyler Parton"
    username: ""
    year: 2023
  - name: "Sreynit  Khatt"
    username: ""
    year: 2023
