secret_key: "123"
use_shibboleth: False
use_tracy: False
use_banner: False
override_file: "local-override.yml"
default_user: "ramsayb2"
celts_admin_contact: "bramsayr@gmail.com"

db:
    name: "celts"
    host: "db"
    username: "celts_user"
    password: "password"

mail:
    enabled: True
    server: "smtp.gmail.com" # use smtp.gmail.com for gmail, mail.berea.edu for Berea
    port: 465                # use port 465 for gmail, use 25 for Berea
    username: 'bramsayr@gmail.com'             # add the email of the sender (for gmail)
    password: 'celtsTest'             # Add the password of the sender (for gmail)
    tls: False
    ssl: True
    default_sender: 'bramsayr@gmail.com' #FIXME: Add sender email address
    override_addr: "bramsayr@gmail.com"
    reply_to_address: "bramsayr@gmail.com"
