secret_key: "123"
use_shibboleth: False
use_tracy: False
use_banner: False
override_file: "local-override.yml"
default_user: "ramsayb2"
celts_admin_contact: "bramsayr@gmail.com"

db:
    name: "celts"
    host: "db"
    username: "celts_user"
    password: "password"

mail:
    enabled: True
    server: "smtp.gmail.com" # use smtp.gmail.com for gmail, mail.berea.edu for Berea
    port: 465                # use port 465 for gmail, use 25 for Berea
    admin_username: 'bramsayr@gmail.com'      # add the email of the sender (Admin) (for gmail)
    admin_password: 'celtsTest'             # Add the password of the sender (for gmail)
    staff_username: 'sceggenh@gmail.com'   # the email of the sender (celtsStudentStaff)
    staff_password: 'celtsTest2'
    tls: False
    ssl: True
    default_sender: 'bramsayr@gmail.com' #FIXME: Add sender email address
    override_addr: "j5u6j9w6v1h0p3g1@bereacs.slack.com"
    reply_to_address: "j5u6j9w6v1h0p3g1@bereacs.slack.com"
