secret_key: "123"
use_shibboleth: False
use_tracy: False
use_banner: False
override_file: "local-override.yml"
default_user: "ramsayb2"
celts_admin_contact: "celts@berea.edu"

db:
    name: "celts"
    host: "db"
    username: "celts_user"
    password: "password"

mail:
    enabled: False
    server: "smtp.gmail.com" # use smtp.gmail.com for gmail, mail.berea.edu for Berea
    port: 465                # use port 465 for gmail, use 25 for Berea
    username: ''             # add the email of the sender (for gmail)
    password: ''             # Add the password of the sender (for gmail)
    tls: False
    ssl: True
    default_sender: '' #FIXME: Add sender email address
    override_addr: "j5u6j9w6v1h0p3g1@bereacs.slack.com"
    reply_to_address: "j5u6j9w6v1h0p3g1@bereacs.slack.com"


contributors:
  - name: "Scott Heggen"
    username: ""
    year: Team Lead
  - name: "Brian Ramsay"
    username: ""
    year: Software Engineer
  - name: "Alex Bryant"
    username: ""
    year: Software Engineer
  - name: "Hailey Bevins"
    username: ""
    year: 2020
  - name: "Guillermo Cruz"
    username: ""
    year: 2021
  - name: "Ela Jamali"
    username: ""
    year: 2021
  - name: "Will Romano"
    username: ""
    year: 2021
  - name: "May Jue"
    username: ""
    year: 2021
  - name: "Shageldi Ovezov"
    username: ""
    year: 2022
  - name: "Sandesh Lamichhane "
    username: ""
    year: 2022
  - name: "Hila Manalai"
    username: ""
    year: 2022
  - name: "Luis Riera"
    username: ""
    year: 2022
  - name: "Lisandro Padron"
    username: ""
    year: 2022
  - name: "Audrey Craft"
    username: ""
    year: 2022
  - name: "Liberty Muposta"
    username: ""
    year: 2022
  - name: "Ebenezer Ayisi"
    username: ""
    year: 2023
  - name: "Gaston Jarju"
    username: ""
    year: 2023
  - name: "Karina Agliullova"
    username: ""
    year: 2023
  - name: "Zach Neill"
    username: ""
    year: 2023
  - name: "Tyler Parton"
    username: ""
    year: 2023
  - name: "Sreynit  Khatt"
    username: ""
    year: 2023
