use_shibboleth: True
show_queries: False

MAIL_ENABLED: True
MAIL_SERVER: "mail.berea.edu"
MAIL_PORT: 587
MAIL_USERNAME: 'ssdt@berea.edu'
MAIL_PASSWORD: ''
MAIL_USE_TLS: True
MAIL_USE_SSL: False
MAIL_DEFAULT_SENDER: 'support@bereacollege.onmicrosoft.com'
MAIL_OVERRIDE_ALL: ""
MAIL_REPLY_TO_ADDRESS: "celts@berea.edu"
