use_shibboleth: False
use_tracy: True
use_banner: True

mail:
    enabled: False
    server: "mail.berea.edu"
    port: 25
    tls: False
    ssl: False
    reply_to_address: "celts@berea.edu"
    default_sender: "support@bereacollege.onmicrosoft.com"
