secret_key: "123"
use_shibboleth: False
use_tracy: False
use_banner: False
default_user: "ramsayb2"
celts_admin_contact: "celts@berea.edu"
show_queries: True
test_entry: "Testing"

MAIL_SUPPRESS_SEND: True

db:
    name: "celts"
    host: "db"
    username: "celts_user"
    password: "password"

mail:
    enabled: False
    server: "smtp.gmail.com" # use smtp.gmail.com for gmail, mail.berea.edu for Berea
    port: 465                # use port 465 for gmail, use 25 for Berea
    username: ''             # add the email of the sender (for gmail)
    password: ''             # Add the password of the sender (for gmail)
    tls: False
    ssl: True
    default_sender: '' #FIXME: Add sender email address
    override_addr: "j5u6j9w6v1h0p3g1@bereacs.slack.com"
    reply_to_address: "j5u6j9w6v1h0p3g1@bereacs.slack.com"


contributors:
  - name: "Scott Heggen"
    role: Team Lead
  - name: "Brian Ramsay"
    role: "Team Lead"
  - name: "Alex Bryant"
    role: "Team Lead"
  - name: "Hailey Bevins"
    role: "Software Engineer"
  - name: "Guillermo Cruz"
    role: "Software Engineer"
  - name: "Ela Jamali"
    role: "Software Engineer"
  - name: "Will Romano"
    role: "Software Engineer"
  - name: "May Jue"
    role: "Software Engineer"
  - name: "Shageldi Ovezov"
    role: "Software Engineer"
  - name: "Sandesh Lamichhane "
    role: "Software Engineer"
  - name: "Hila Manalai"
    role: "Software Engineer"
  - name: "Luis Riera"
    role: "Software Engineer"
  - name: "Lisandro Padron"
    role: "Software Engineer"
  - name: "Audrey Craft"
    role: "Software Engineer"
  - name: "Liberty Muposta"
    role: "Software Engineer"
  - name: "Ebenezer Ayisi"
    role: "Software Engineer"
  - name: "Gaston Jarju"
    role: "Software Engineer"
  - name: "Karina Agliullova"
    role: "Software Engineer"
  - name: "Zach Neill"
    role: "Software Engineer"
  - name: "Tyler Parton"
    role: "Software Engineer"
  - name: "Sreynit  Khatt"
    role: "Software Engineer"
