class Event(baseModel):
    eventID = PrimaryKeyField()
    eventName = CharField(null=False)
    term_id = ForeignKeyField(null=False)
    timeStart = CharField(null=False)
    timeEnd = CharField(null=False)
    location = CharField(null=False)
    program_id = ForeignKeyField(null=False)
    isRsvpRequired = BooleanField(null=False)
    isService = BooleanField(null=False)
    isRequiredForProgram = BooleanField(null=False)
    description = CharField(null=False)
    startDate = DateField(null=True)
    endDate = DateField(null=True)
    files = CharField(null=True)
